import type { Category, FamilyState } from "./types";

const expenseNames = [
  "Жильё",
  "Продукты",
  "Кафе и рестораны",
  "Транспорт",
  "Связь и интернет",
  "Визы и документы",
  "Здоровье",
  "Одежда",
  "Развлечения",
  "Обучение",
  "Техника",
  "Подписки",
  "Реклама и работа",
  "Путешествия",
  "Подарки",
  "Непредвиденные расходы",
  "Другое",
] as const;

const incomeNames = [
  "Работа Ивана",
  "Работа Алины",
  "Репетиторство",
  "Продажи",
  "Услуги в сфере ИИ",
  "Блог и YouTube",
  "Подарки",
  "Возвраты",
  "Другое",
] as const;

const palette = [
  "#6ee7b7",
  "#60a5fa",
  "#fbbf24",
  "#fb7185",
  "#a78bfa",
  "#22d3ee",
];

export const defaultCategories: Category[] = [
  ...expenseNames.map((name, index) => ({
    id: `expense-${index + 1}`,
    name,
    type: "expense" as const,
    archived: false,
    color: palette[index % palette.length],
    isDefault: true,
  })),
  ...incomeNames.map((name, index) => ({
    id: `income-${index + 1}`,
    name,
    type: "income" as const,
    archived: false,
    color: palette[(index + 2) % palette.length],
    isDefault: true,
  })),
];

const categoryId = (name: string, type: "income" | "expense") =>
  defaultCategories.find(
    (category) => category.name === name && category.type === type,
  )?.id ?? "expense-17";

export const createDemoState = (): FamilyState => ({
  baseCurrency: "USD",
  currentUser: "Иван",
  lastExport: null,
  categories: defaultCategories,
  operations: [
    {
      id: "op-1",
      type: "income",
      amount: 2800,
      currency: "USD",
      rate: 1,
      baseAmount: 2800,
      date: "2026-08-08",
      person: "Иван",
      categoryId: categoryId("Работа Ивана", "income"),
      account: "Wise",
      comment: "Основной проект",
      createdAt: "2026-08-08T09:30:00.000Z",
      author: "Иван",
    },
    {
      id: "op-2",
      type: "income",
      amount: 78000,
      currency: "RUB",
      rate: 0.0125,
      baseAmount: 975,
      date: "2026-08-06",
      person: "Алина",
      categoryId: categoryId("Репетиторство", "income"),
      account: "Карта RUB",
      comment: "Занятия за первую неделю",
      createdAt: "2026-08-06T12:00:00.000Z",
      author: "Алина",
    },
    {
      id: "op-3",
      type: "expense",
      amount: 9200000,
      currency: "VND",
      rate: 0.0000383,
      baseAmount: 352.36,
      date: "2026-08-05",
      person: "Общее",
      categoryId: categoryId("Жильё", "expense"),
      account: "Наличные VND",
      comment: "Аренда квартиры",
      createdAt: "2026-08-05T10:15:00.000Z",
      author: "Иван",
    },
    {
      id: "op-4",
      type: "expense",
      amount: 1685000,
      currency: "VND",
      rate: 0.0000383,
      baseAmount: 64.54,
      date: "2026-08-09",
      person: "Общее",
      categoryId: categoryId("Продукты", "expense"),
      account: "Карта VND",
      comment: "Продукты на неделю",
      createdAt: "2026-08-09T16:20:00.000Z",
      author: "Алина",
    },
    {
      id: "op-5",
      type: "expense",
      amount: 7800,
      currency: "RUB",
      rate: 0.0125,
      baseAmount: 97.5,
      date: "2026-08-07",
      person: "Иван",
      categoryId: categoryId("Подписки", "expense"),
      account: "Карта RUB",
      comment: "Рабочие сервисы",
      createdAt: "2026-08-07T08:00:00.000Z",
      author: "Иван",
    },
    {
      id: "op-6",
      type: "expense",
      amount: 85,
      currency: "USD",
      rate: 1,
      baseAmount: 85,
      date: "2026-08-04",
      person: "Алина",
      categoryId: categoryId("Обучение", "expense"),
      account: "Wise",
      comment: "Курс английского",
      createdAt: "2026-08-04T15:40:00.000Z",
      author: "Алина",
    },
    {
      id: "op-7",
      type: "expense",
      amount: 650000,
      currency: "VND",
      rate: 0.0000383,
      baseAmount: 24.9,
      date: "2026-07-25",
      person: "Общее",
      categoryId: categoryId("Кафе и рестораны", "expense"),
      account: "Наличные VND",
      comment: "Ужин",
      createdAt: "2026-07-25T19:10:00.000Z",
      author: "Алина",
    },
    {
      id: "op-8",
      type: "income",
      amount: 400,
      currency: "USD",
      rate: 1,
      baseAmount: 400,
      date: "2026-07-18",
      person: "Иван",
      categoryId: categoryId("Услуги в сфере ИИ", "income"),
      account: "PayPal",
      comment: "Консультация",
      createdAt: "2026-07-18T11:00:00.000Z",
      author: "Иван",
    },
  ],
  budgets: [
    {
      id: "budget-1",
      month: "2026-08",
      categoryId: categoryId("Жильё", "expense"),
      limit: 500,
      currency: "USD",
    },
    {
      id: "budget-2",
      month: "2026-08",
      categoryId: categoryId("Продукты", "expense"),
      limit: 250,
      currency: "USD",
    },
    {
      id: "budget-3",
      month: "2026-08",
      categoryId: categoryId("Кафе и рестораны", "expense"),
      limit: 120,
      currency: "USD",
    },
    {
      id: "budget-4",
      month: "2026-08",
      categoryId: categoryId("Подписки", "expense"),
      limit: 100,
      currency: "USD",
    },
    {
      id: "budget-5",
      month: "2026-08",
      categoryId: categoryId("Обучение", "expense"),
      limit: 180,
      currency: "USD",
    },
    {
      id: "budget-6",
      month: "2026-07",
      categoryId: categoryId("Жильё", "expense"),
      limit: 500,
      currency: "USD",
    },
    {
      id: "budget-7",
      month: "2026-07",
      categoryId: categoryId("Продукты", "expense"),
      limit: 230,
      currency: "USD",
    },
    {
      id: "budget-8",
      month: "2026-07",
      categoryId: categoryId("Кафе и рестораны", "expense"),
      limit: 100,
      currency: "USD",
    },
  ],
  goals: [
    {
      id: "goal-1",
      title: "Резерв на экстренный случай",
      description: "Подушка на 4 месяца спокойной жизни",
      target: 10000,
      current: 6250,
      currency: "USD",
      deadline: "2027-01-31",
      owner: "Вместе",
      status: "active",
      color: "#34d399",
      icon: "shield",
    },
    {
      id: "goal-2",
      title: "Бюджет на переезд",
      description: "Депозит, билеты и первые расходы",
      target: 6000,
      current: 2100,
      currency: "USD",
      deadline: "2026-12-15",
      owner: "Вместе",
      status: "active",
      color: "#60a5fa",
      icon: "home",
    },
    {
      id: "goal-3",
      title: "Техника для блога",
      description: "Камера, свет и микрофон",
      target: 180000,
      current: 94000,
      currency: "RUB",
      deadline: "2026-11-01",
      owner: "Алина",
      status: "active",
      color: "#fbbf24",
      icon: "camera",
    },
  ],
  tasks: [
    {
      id: "task-1",
      title: "Продлить визы",
      description: "Подготовить фото и копии документов",
      owner: "Вместе",
      dueDate: "2026-08-18",
      priority: "high",
      status: "progress",
      category: "Документы",
      createdAt: "2026-08-02T10:00:00.000Z",
    },
    {
      id: "task-2",
      title: "Выбрать страховку",
      description: "Сравнить три подходящих варианта",
      owner: "Иван",
      dueDate: "2026-08-14",
      priority: "medium",
      status: "planned",
      category: "Здоровье",
      createdAt: "2026-08-03T10:00:00.000Z",
    },
    {
      id: "task-3",
      title: "Спланировать поездку в Дананг",
      description: "Отель, билеты и бюджет",
      owner: "Алина",
      dueDate: "2026-08-27",
      priority: "low",
      status: "planned",
      category: "Путешествия",
      createdAt: "2026-08-05T10:00:00.000Z",
    },
    {
      id: "task-4",
      title: "Оплатить интернет",
      description: "Годовой тариф со скидкой",
      owner: "Иван",
      dueDate: "2026-08-08",
      priority: "medium",
      status: "done",
      category: "Дом",
      createdAt: "2026-08-01T10:00:00.000Z",
    },
  ],
  notes: [
    {
      id: "note-1",
      title: "Важные номера",
      text: "Страховая: +84 28 3829 8520\nХозяин квартиры: Minh",
      author: "Иван",
      visibility: "shared",
      tags: ["контакты", "важное"],
      createdAt: "2026-08-01T08:00:00.000Z",
      updatedAt: "2026-08-08T08:00:00.000Z",
      pinned: true,
    },
    {
      id: "note-2",
      title: "Идеи для подарка",
      text: "Книга по фотографии, новый штатив или день без телефона.",
      author: "Алина",
      visibility: "personal",
      tags: ["идеи"],
      createdAt: "2026-08-03T08:00:00.000Z",
      updatedAt: "2026-08-03T08:00:00.000Z",
      pinned: false,
    },
    {
      id: "note-3",
      title: "Правила бюджета на август",
      text: "Сначала откладываем 20% дохода, крупные покупки обсуждаем заранее.",
      author: "Алина",
      visibility: "shared",
      tags: ["финансы", "август"],
      createdAt: "2026-08-04T08:00:00.000Z",
      updatedAt: "2026-08-06T08:00:00.000Z",
      pinned: true,
    },
  ],
});
